In [2]:
from pyfm import pylibfm
from sklearn.feature_extraction import DictVectorizer
import numpy as np
train = [
    {"user": "1", "item": "5", "age": 19},
    {"user": "2", "item": "43", "age": 33},
    {"user": "3", "item": "20", "age": 55},
    {"user": "4", "item": "10", "age": 20},
]
v = DictVectorizer()
X = v.fit_transform(train)
print(X.toarray())
y = np.repeat(1.0,X.shape[0])
fm = pylibfm.FM()
fm.fit(X,y)
fm.predict(v.transform({"user": "1", "item": "10", "age": 24}))

[[ 19.   0.   0.   0.   1.   1.   0.   0.   0.]
 [ 33.   0.   0.   1.   0.   0.   1.   0.   0.]
 [ 55.   0.   1.   0.   0.   0.   0.   1.   0.]
 [ 20.   1.   0.   0.   0.   0.   0.   0.   1.]]
Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training log loss: 0.22230


array([ 0.9833513])

In [9]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from pyfm import pylibfm

# Read in data
def loadData(filename,path="C:/Users/Fizik/Downloads/coursera/nir/nir/movielens/ml-100k/"):
    data = []
    y = []
    users=set()
    items=set()
    with open(path+filename) as f:
        for line in f:
            (user,movieid,rating,ts)=line.split('\t')
            data.append({ "user_id": str(user), "movie_id": str(movieid)})
            y.append(float(rating))
            users.add(user)
            items.add(movieid)

    return (data, np.array(y), users, items)

(train_data, y_train, train_users, train_items) = loadData("ua.base")
(test_data, y_test, test_users, test_items) = loadData("ua.test")
v = DictVectorizer()
X_train = v.fit_transform(train_data)
X_test = v.transform(test_data)

# Build and train a Factorization Machine
fm = pylibfm.FM(num_factors=10, num_iter=100, verbose=True, task="regression", initial_learning_rate=0.001, learning_rate_schedule="optimal")

fm.fit(X_train,y_train)

Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training MSE: 0.59457
-- Epoch 2
Training MSE: 0.51814
-- Epoch 3
Training MSE: 0.49046
-- Epoch 4
Training MSE: 0.47470
-- Epoch 5
Training MSE: 0.46422
-- Epoch 6
Training MSE: 0.45679
-- Epoch 7
Training MSE: 0.45113
-- Epoch 8
Training MSE: 0.44655
-- Epoch 9
Training MSE: 0.44270
-- Epoch 10
Training MSE: 0.43960
-- Epoch 11
Training MSE: 0.43688
-- Epoch 12
Training MSE: 0.43448
-- Epoch 13
Training MSE: 0.43231
-- Epoch 14
Training MSE: 0.43041
-- Epoch 15
Training MSE: 0.42867
-- Epoch 16
Training MSE: 0.42702
-- Epoch 17
Training MSE: 0.42547
-- Epoch 18
Training MSE: 0.42407
-- Epoch 19
Training MSE: 0.42266
-- Epoch 20
Training MSE: 0.42139
-- Epoch 21
Training MSE: 0.42022
-- Epoch 22
Training MSE: 0.41898
-- Epoch 23
Training MSE: 0.41783
-- Epoch 24
Training MSE: 0.41664
-- Epoch 25
Training MSE: 0.41550
-- Epoch 26
Training MSE: 0.41425
-- Epoch 27
Training MSE: 0.41310
-- Epoch 28
Tra

ValueError: I/O operation on closed file

In [10]:
preds = fm.predict(X_test)
from sklearn.metrics import mean_squared_error
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print("FM MSE: %.4f" % mean_squared_error(y_test,preds))
preds = [int(x) for x in preds]
print("precision_score: %.4f" % precision_score(y_test,preds, average='weighted'))
print("recall_score: %.4f" % recall_score(y_test,preds, average='weighted'))

FM MSE: 0.9128
precision_score: 0.4450
recall_score: 0.3249


In [25]:
id = np.argsort(preds)[::-1]
for k in [50, 100, 1000, 5000, 8000]:
    ids = id[:k]
    print("k: %s ,precision_score: %.4f" % (k, precision_score([y_test[i] for i in ids],[preds[i] for i in ids], average='weighted')))
    print("K: %s ,recall_score: %.4f" % (k,k*1.0/9430*recall_score([y_test[i] for i in ids],[preds[i] for i in ids], average='weighted')))

k: 50 ,precision_score: 0.5672
K: 50 ,recall_score: 0.0031
k: 100 ,precision_score: 0.5289
K: 100 ,recall_score: 0.0058
k: 1000 ,precision_score: 0.4776
K: 1000 ,recall_score: 0.0426
k: 5000 ,precision_score: 0.4420
K: 5000 ,recall_score: 0.1830
k: 8000 ,precision_score: 0.4113
K: 8000 ,recall_score: 0.2796


In [20]:
print [y_test[i] for i in ids],[preds[i] for i in ids]

[5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0] [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [32]:
print X_train.shape
print len(y_train)
print len(preds)
print X_test.shape

(90570, 2623)
90570
9430
(9430, 2623)


In [34]:
print X_test

  (0, 793)	1.0
  (0, 1680)	1.0
  (1, 937)	1.0
  (1, 1680)	1.0
  (2, 1248)	1.0
  (2, 1680)	1.0
  (3, 190)	1.0
  (3, 1680)	1.0
  (4, 612)	1.0
  (4, 1680)	1.0
  (5, 667)	1.0
  (5, 1680)	1.0
  (6, 761)	1.0
  (6, 1680)	1.0
  (7, 780)	1.0
  (7, 1680)	1.0
  (8, 796)	1.0
  (8, 1680)	1.0
  (9, 865)	1.0
  (9, 1680)	1.0
  (10, 334)	1.0
  (10, 1791)	1.0
  (11, 1126)	1.0
  (11, 1791)	1.0
  (12, 850)	1.0
  :	:
  (9417, 2616)	1.0
  (9418, 1242)	1.0
  (9418, 2616)	1.0
  (9419, 1254)	1.0
  (9419, 2616)	1.0
  (9420, 112)	1.0
  (9420, 2617)	1.0
  (9421, 1214)	1.0
  (9421, 2617)	1.0
  (9422, 124)	1.0
  (9422, 2617)	1.0
  (9423, 777)	1.0
  (9423, 2617)	1.0
  (9424, 810)	1.0
  (9424, 2617)	1.0
  (9425, 829)	1.0
  (9425, 2617)	1.0
  (9426, 966)	1.0
  (9426, 2617)	1.0
  (9427, 1204)	1.0
  (9427, 2617)	1.0
  (9428, 1468)	1.0
  (9428, 2617)	1.0
  (9429, 76)	1.0
  (9429, 2617)	1.0


classcification

In [8]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.cross_validation import train_test_split
from pyfm import pylibfm

from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000,n_features=100, n_clusters_per_class=1)
data = [ {v: k for k, v in dict(zip(i, range(len(i)))).items()}  for i in X]

X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.1, random_state=42)

v = DictVectorizer()
X_train = v.fit_transform(X_train)
X_test = v.transform(X_test)

fm = pylibfm.FM(num_factors=50, num_iter=10, verbose=True, task="classification", initial_learning_rate=0.0001, learning_rate_schedule="optimal")

fm.fit(X_train,y_train)

Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training log loss: 1.94249
-- Epoch 2
Training log loss: 1.64100
-- Epoch 3
Training log loss: 1.39210
-- Epoch 4
Training log loss: 1.18709
-- Epoch 5
Training log loss: 1.01753
-- Epoch 6
Training log loss: 0.87650
-- Epoch 7
Training log loss: 0.75867
-- Epoch 8
Training log loss: 0.65960
-- Epoch 9
Training log loss: 0.57569
-- Epoch 10
Training log loss: 0.50416


In [9]:
from sklearn.metrics import log_loss
print "Validation log loss: %.4f" % log_loss(y_test,fm.predict(X_test))

Validation log loss: 1.3999


10M

In [ ]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from pyfm import pylibfm

# Read in data
def loadData(filename,path="C:/Users/Fizik/Downloads/coursera/nir/nir/movielens/"):
    data = []
    y = []
    users=set()
    items=set()
    with open(path+filename) as f:
        for line in f:
            (user,movieid,rating,ts)=line.split('::')
            data.append({ "user_id": str(user), "movie_id": str(movieid)})
            y.append(float(rating))
            users.add(user)
            items.add(movieid)

    return (data, np.array(y), users, items)

(train_data, y_train, train_users, train_items) = loadData("rb.train")
(test_data, y_test, test_users, test_items) = loadData("rb.test")
v = DictVectorizer()
X_train = v.fit_transform(train_data)
X_test = v.transform(test_data)

# Build and train a Factorization Machine
fm = pylibfm.FM(num_factors=10, num_iter=100, verbose=True, task="regression", initial_learning_rate=0.1, learning_rate_schedule="optimal")

fm.fit(X_train,y_train)

Creating validation dataset of 0.01 of training for adaptive regularization


In [ ]:
preds = fm.predict(X_test)
from sklearn.metrics import mean_squared_error
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print("FM MSE: %.4f" % mean_squared_error(y_test,preds))
preds = [int(x) for x in preds]
print("precision_score: %.4f" % precision_score(y_test,preds, average='weighted'))
print("recall_score: %.4f" % recall_score(y_test,preds, average='weighted'))