In [8]:
import pandas as pd
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv('movielens/ml-100k/u.user', sep='|', names=u_cols,
                    encoding='latin-1')

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('movielens/ml-100k/u.data', sep='\t', names=r_cols,
                      encoding='latin-1')

# the movies file contains columns indicating the movie's genres
# let's only load the first five columns of the file with usecols
m_cols = ['movie_id', 'title', 'release_date', 'video_release_date', 'imdb_url']
movies = pd.read_csv('movielens/ml-100k/u.item', sep='|', names=m_cols, usecols=range(5),
                     encoding='latin-1')

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 5 columns):
movie_id              1682 non-null int64
title                 1682 non-null object
release_date          1681 non-null object
video_release_date    0 non-null float64
imdb_url              1679 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 65.8+ KB


In [10]:
movies.dtypes

movie_id                int64
title                  object
release_date           object
video_release_date    float64
imdb_url               object
dtype: object

In [11]:
users.describe()

user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [12]:
movies.head()

movie_id              title release_date  video_release_date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   
3         4  Get Shorty (1995)  01-Jan-1995                 NaN   
4         5     Copycat (1995)  01-Jan-1995                 NaN   

                                            imdb_url  
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...  
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...  
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...  
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...  
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)

In [1]:
import pandas as pd
import numpy as np

In [18]:
a = pd.DataFrame([[1,0,0],[0,0,2],[0,0,0]])

In [19]:
a

0  1  2
0  1  0  0
1  0  0  2
2  0  0  0

In [20]:
c = a.to_sparse()

In [21]:
type(c)

pandas.sparse.frame.SparseDataFrame

In [22]:
type(c)

pandas.sparse.frame.SparseDataFrame

In [23]:
g = a.to_sparse()

In [24]:
type(g.to_sparse())

pandas.sparse.frame.SparseDataFrame

In [25]:
import scipy.sparse as sps

In [26]:
mat = sps.coo_matrix((a.values))

In [27]:
mat

<3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 2 stored elements in COOrdinate format>

In [28]:
mat.todense()

matrix([[1, 0, 0],
        [0, 0, 2],
        [0, 0, 0]], dtype=int64)

In [29]:
mat.col

array([0, 2])

In [35]:
mat.transpose()

<3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 2 stored elements in COOrdinate format>

In [36]:
mat.todense()

matrix([[1, 0, 0],
        [0, 0, 2],
        [0, 0, 0]], dtype=int64)

In [37]:
mat.transpose().todense()

matrix([[1, 0, 0],
        [0, 0, 0],
        [0, 2, 0]], dtype=int64)

In [ ]:
mat.